create table CREDITOGESTAO_LIMITES_CHESPECIAL(
  ID bigint auto_increment NOT NULL,	
  IDRISCO_CARGA_CENTRAL varchar(100) NOT NULL,
  COOPERATIVA numeric NOT NULL,
  NRCONTA numeric NOT NULL,
  NRCONTRATO decimal(15,0) NOT NULL,
  TAXAJUROSMES numeric NOT NULL,
  DATAINICIOVIGENCIA timestamp DEFAULT NULL,
  DATAFINALVIGENCIA timestamp NOT NULL,
  VALORCONTRATO numeric NOT NULL,
  VALORUTILIZADO numeric NOT NULL,
  VALORNAOUTILIZADO numeric NOT NULL,
  DATAREFERENCIA timestamp NOT NULL,
  SALDOS_JTS_OID numeric NOT NULL,
  DHREGISTROTD timestamp NOT NULL,
  PRIMARY KEY (ID)
);

create table CREDITOGESTAO_RISCO_CARGA_OPERACAO(
	cdcarga_operacao bigint auto_increment NOT NULL,
  idrisco_carga_central varchar(100) NOT NULL,
  idCooperativa numeric NOT NULL,
  nrdconta numeric(11) NOT NULL,
  nrcontrato numeric(15) NOT NULL,
  dsctacos VARCHAR(20) DEFAULT '1612000',
  dsorgrec VARCHAR(10) DEFAULT '0199',
  nrtaxidx numeric(10) DEFAULT 21,
  nrperidx numeric(10) DEFAULT 100,
  nrvarcam numeric(10) DEFAULT 790,
  nrcepcon numeric(8) NOT NULL,
  nrtaxeft numeric(10,2) NOT NULL,
  dtinictr TIMESTAMP NOT NULL,
  cdnatope numeric(2) DEFAULT 01,
  dscaresp varchar(50) DEFAULT NULL,
  vlcontrato numeric(15, 2) NOT NULL,
  flprejuz numeric(1) DEFAULT NULL,
  qtdiaatr numeric(10) DEFAULT NULL,
  tpcartao numeric(1) DEFAULT NULL,
  qtparcela numeric(5) DEFAULT NULL,
  nrcontrato_principal numeric(15) NOT NULL,
  dtsaida TIMESTAMP DEFAULT NULL,
  tpcontrato numeric(5) DEFAULT 1,
  vljuros_suspenso numeric(15, 2) NOT NULL,
  cdproduto_contabil numeric(3) NOT NULL,
  dtvencimento TIMESTAMP NOT NULL, 
  dtproxima_parcela TIMESTAMP DEFAULT NULL,
  vlproxima_parcela numeric(25,2) DEFAULT NULL,
  cdmodalidade VARCHAR(4) NOT NULL,
  cdrisco_refinanciamento numeric(5) DEFAULT NULL,
  vlsaldo_limite numeric(15, 2) NOT NULL,
  idsistema_origem numeric(2) DEFAULT 2,
  cdCif numeric(1) NOT NULL,
  vlcontabil_bruto numeric(19, 2) NOT NULL,
  qtparcela_paga NUMERIC(3) DEFAULT NULL,
  vlparcela_paga NUMERIC(19, 2) DEFAULT NULL,
  nrversao_contrato NUMERIC(2) DEFAULT NULL,
  tprenegociacao NUMERIC(1) DEFAULT NULL,
  pedesconto_renegociacao NUMERIC(5,2) DEFAULT NULL,
  flativo_problematico NUMERIC(1) NOT NULL,
  vlperda_acumulada NUMERIC(19,2) DEFAULT NULL,
  id_creditogestao_limites_chespecial bigint not null,
  PRIMARY KEY (cdcarga_operacao),
  FOREIGN KEY (id_creditogestao_limites_chespecial) references CREDITOGESTAO_LIMITES_CHESPECIAL(ID)
);

CREATE TABLE CREDITOGESTAO_RISCO_CARGA_OPERACAO_VENCIMENTO(
  id bigint auto_increment NOT NULL,
  idrisco_carga_central varchar(100) NOT NULL,
  cdcarga_operacao NUMERIC(15) NOT NULL,
  cdvencimento NUMERIC(15) NOT NULL,
  vlvencimento NUMERIC(19,2) NOT NULL,
  PRIMARY KEY (id)
);